---
title: "Landis RF Data Prep"
author: "Wesley Rancher"
date: "2025-03-28"
output: html_document
editor_options: 
  chunk_output_type: console
---

Building dataset for random forest on Landis output (target variable: aboveground C from biomass output)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(purrr)
library(dplyr)
library(stringr)
library(tidyr)
library(terra)
```

Files and directories

```{r}
response_dir <- "F:/Rancher_Sims_Full_Landscape/interior_hist_ncar_3.10.2025/biomass/"
main_input_dir <- "F:/Rancher_Sims_Full_Landscape/interior_hist_ncar_3.10.2025/" #could be many reps with recursive flag 

#vectors
bounds <- vect("F:/randomForest_Landis/input/shp/FullLandscapeV3_082722.shp")
pts <- vect("F:/randomForest_Landis/input/shp/cafiPlotsCropped.shp")#already within full landscape bounds
```

Response Variable

```{r}
species <- c('BlackSpruce', 'WhiteSpruce', 'PaperBirch', 'QuakingAspen')
biomass_files <- list.files(path = response_dir, pattern = paste(species, collapse = "|"), full.names = TRUE)

clean_biomass_raster <- function(file){
  #grab species and scenario
  file_name <- file.path(file)
  splitname <- strsplit(file_name, "/")[[1]]
  var <- strsplit(splitname[5], "-")[[1]][1]
  spp <- gsub(".*biomass/(\\w+)-.*", "\\1", file_name)
  scenario <- gsub(".*interior_(\\w+)_.*", "\\1", file_name)
  #add replicate?
  
  #project
  r <- rast(file)
  flipped <- flip(r, direction='vertical')#its upside down
  
  ext(flipped) <- ext(bounds)
  crs(flipped) <- 'EPSG:3338'
  
  #crop 
  clipped <- mask(flipped, bounds)
  vals <- extract(clipped, pts)
  vals_df <- as.data.frame(vals)
  
  vals_df$spp <- spp
  vals_df$scenario <- scenario
  vals_df$ag_carbon <- vals_df$Layer_1*0.47#convert to carbon
  vals_df$PSP <- pts$PSP
  vals_df <- vals_df%>%select(-Layer_1, -ID)
  rm(r, flipped, clipped)
  return(vals_df)
}
extracted_vals_carbon_list <- lapply(biomass_files, clean_biomass_raster)
extracted_vals_carbon_df <- do.call(rbind, extracted_vals_carbon_list)#all years in one df (many to many when joining)
```

Training Data (Input tiffs)

```{r}
training_tiffs <- list.files(path = main_input_dir, pattern = "\\.tif$", full.names = TRUE)

clean_input_raster <- function(file){
  file_name <- file.path(file)
  splitname <- strsplit(file_name, "/")[[1]]
  var <- strsplit(splitname[4], "_")[[1]][1]
  scenario <- gsub(".*interior_(\\w+)_.*", "\\1", file_name)
  
  #naming convention different for some maps (this grabs the second item from splitname)
  if (var=="AK") {
    var <- strsplit(splitname[4], "_")[[1]][2]
  }
  
  #project, clip, extract vals
  r <- rast(file)
  ext(r) <- ext(bounds)
  crs(r) <- 'EPSG:3338'
  
  clipped <- mask(r, bounds)
  vals <- extract(clipped, pts)
  vals <- as.data.frame(vals)
  
  vals$var <- var
  vals$scenario <- scenario
  vals$PSP <- pts$PSP
  vals <- vals%>%select(-ID)
  names(vals)[1] <- "value"
  
  rm(r, clipped)
  return(vals)
}

extracted_vals_tiffs_list <- lapply(training_tiffs, clean_input_raster)
extracted_vals_tiffs_df <- do.call(rbind, extracted_vals_tiffs_list) %>%
  #remove unnecessary maps
  filter(var != "AllOnes", var != "AllZeros", var != "AllOnes", var != "MapCodes", var != "Suppression")
```

Training data (Extension imgs from SCRPPLE and DGS)

```{r}
all_files <- list.files(path = main_input_dir, full.names = TRUE, recursive = TRUE)
dgs_map_files <- all_files[grepl("DGS", all_files) & grepl("\\.img$", all_files)]
scrpple_map_files <- all_files[grepl("social-climate-fire", all_files) & grepl("\\.tif$", all_files)]
#there will be a many to many warning when joining because of monthly dgs output

#necessary to calculate time since fire or no since this across all years?
tsf <- function(file){
}

#function to clean extension outputs
clean_raster <- function(file){
  #grab extension
  file_name <- file.path(file)
  splitname <- strsplit(file_name, "/")[[1]]
  ext <- splitname[4]
  var <- strsplit(splitname[5], "-")[[1]][1]
  scenario <- gsub(".*interior_(\\w+)_.*", "\\1", file_name)
  #add replicate?
  
  #naming convention for scrpple out since seperated by dashes
  if (ext == "social-climate-fire"){
    var <- paste0(strsplit(splitname[5], "-")[[1]][1], strsplit(splitname[5], "-")[[1]][2])
  }
  
  #project
  r <- rast(file)
  flipped <- flip(r, direction='vertical')#its upside down
  
  ext(flipped) <- ext(bounds)
  crs(flipped) <- 'EPSG:3338'
  
  #crop 
  clipped <- mask(flipped, bounds)
  vals <- extract(clipped, pts)
  vals_df <- as.data.frame(vals)
  
  vals_df$var <- var
  vals_df$scenario <- scenario
  #vals_df$extension <- ext
  vals_df$PSP <- pts$PSP
  vals_df <- vals_df%>%select(-ID)
  names(vals_df)[1] <- "value"
  rm(r, flipped, clipped)
  return(vals_df)
}
extracted_vals_dgs_imgs <- lapply(dgs_map_files, clean_raster)
extracted_vals_scrpple_imgs <- lapply(scrpple_map_files, clean_raster)

extracted_vals_dgs_df <- do.call(rbind, extracted_vals_dgs_imgs)
extracted_vals_scrpple_df <- do.call(rbind, extracted_vals_scrpple_imgs)
```

Training Data (Climate csvs and p-est log)

```{r}
clim_regions <- rast("F:/Rancher_Sims_Full_Landscape/interior_hist_ncar_3.10.2025/AK_ClimateMap_10_Regions.tif")

#climate regions
pts_associated_with_regions <- extract(clim_regions, pts)
pts_associated_with_regions$PSP <- pts$PSP
pts_associated_with_regions <- pts_associated_with_regions%>%select(-ID)
names(pts_associated_with_regions)[1] <- "ClimateRegion"

#p-est log for now
logs <- all_files[grepl("DGS-prob-establish-log", all_files)]#could grab csv patterns
  
process_log <- function(file){
  #patterns for adding to df
  file_name <- file.path(file)
  splitname <- strsplit(file_name, "/")[[1]]
  var <- paste0(strsplit(splitname[4], "-")[[1]][2], strsplit(splitname[4], "-")[[1]][3])
  scenario <- gsub(".*interior_(\\w+)_.*", "\\1", file_name)
  
  #filter to species of interest
  df <- read.csv(file)
  df$SpeciesName <- str_trim(df$SpeciesName)
  df <- df %>% filter(SpeciesName%in%species)#species listed in earlier chunk
  df$GSL <- df$EndGDD <- df$BeginGDD
  
  #join to pts by climate region (something is not quite right here but it'll do)
  joined_df <- df %>% 
    merge(pts_associated_with_regions, by = "ClimateRegion")%>%
    select(GSL, AvgProbEst, PSP)%>%
    pivot_longer(cols = c(GSL, AvgProbEst), 
                 names_to = "var", 
                 values_to = "value")
  joined_df$scenario <- scenario
  return(joined_df)
}
cleaned_pest_log <- process_log(logs)

#trying to keep these dynamic instead of using read csv but it is a bit clunky right now
climate_data <- all_files[grepl("ncar_climate_formatted_AK_V4_historical_dripfix1_precipaddedback-newCL.csv", all_files)]
process_climate <- function(file){
  #patterns for adding to df
  file_name <- file.path(file)
  splitname <- strsplit(file_name, "/")[[1]]
  #var <- paste0(strsplit(splitname[4], "_")[[1]][1], strsplit(splitname[4], "_")[[1]][2],strsplit(splitname[4], "_")[[1]][6])
  scenario <- gsub(".*interior_(\\w+)_.*", "\\1", file_name)
  
  #filter to species of interest
  df <- read.csv(file)
  
  #reshape
  long_df <- df %>% 
    pivot_longer(cols = starts_with("X"), 
                 names_to = "ClimateRegion", 
                 values_to = "value")
  long_df$ClimateRegion <- as.integer(gsub("^X", "", long_df$ClimateRegion)) #remove the leading 'X'
  joined_df <- long_df %>% 
    merge(pts_associated_with_regions, by = "ClimateRegion") %>% 
    rename(var=Variable) %>%
    select(value, var, PSP)
  joined_df$scenario <- scenario
  return(joined_df)
}
cleaned_climate_df <- process_climate(climate_data)
```

Joining into main df

```{r}
main_df <- rbind(extracted_vals_tiffs_df, extracted_vals_dgs_df, extracted_vals_scrpple_df, cleaned_pest_log, cleaned_climate_df)
main_df_na_omit <- main_df %>% na.omit() %>% pivot_wider(names_from = var, values_from = value, values_fn = mean)#average duplicates
unique(main_df$var)

rf_ready_df <- full_join(extracted_vals_carbon_df, main_df_na_omit, by = "PSP")%>%
  select(-scenario.y, -TotalC)%>%
  rename(scenario=scenario.x)

#join to xy for gwrf
pts_df <- as.data.frame(pts)
xy <- pts_df %>% select(Longitude, Latitude, PSP) %>% rename(x=Longitude,y=Latitude)
rf_ready_df2 <- left_join(rf_ready_df, xy, by = "PSP")
rf_ready_df2 <- na.omit(unique(rf_ready_df2))#removing duplicates
write.csv(rf_ready_df2, "F:/randomForest_Landis/output/main_predictor_data.csv", row.names = FALSE)
```




